/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0-beta.9.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AIRecommendationResult {
  'recommendations' : Recommendations,
  'explanations' : Array<string>,
}
export type ExternalBlob = Uint8Array;
export interface Interest {
  'status' : string,
  'recipient' : Principal,
  'sender' : Principal,
}
export interface JobApplication {
  'status' : string,
  'applicant' : Principal,
  'jobId' : bigint,
  'dateApplied' : bigint,
}
export interface JobListing {
  'id' : bigint,
  'experienceLevel' : string,
  'title' : string,
  'jobType' : string,
  'company' : string,
  'category' : string,
  'salaryRange' : [bigint, bigint],
  'location' : string,
}
export interface JobProfile {
  'resume' : [] | [ExternalBlob],
  'name' : string,
  'maxSalary' : bigint,
  'education' : string,
  'profession' : string,
  'minSalary' : bigint,
  'experience' : bigint,
  'location' : string,
}
export interface JobRecommendation {
  'job' : JobListing,
  'matchScore' : bigint,
  'reason' : string,
}
export interface Match {
  'compatibilityScore' : bigint,
  'user1' : Principal,
  'user2' : Principal,
}
export interface MatrimonialProfile {
  'age' : bigint,
  'occupation' : string,
  'name' : string,
  'minAge' : bigint,
  'preferredLocation' : string,
  'maxAge' : bigint,
  'religion' : string,
  'profilePicture' : [] | [ExternalBlob],
}
export interface MatrimonialRecommendation {
  'compatibilityScore' : bigint,
  'profile' : MatrimonialProfile,
  'reason' : string,
}
export interface Message {
  'to' : Principal,
  'content' : string,
  'from' : Principal,
  'timestamp' : bigint,
}
export interface Recommendations {
  'jobs' : Array<JobRecommendation>,
  'matches' : Array<MatrimonialRecommendation>,
}
export interface UserProfile {
  'matrimonialProfile' : [] | [MatrimonialProfile],
  'jobProfile' : [] | [JobProfile],
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  'acceptInterest' : ActorMethod<[bigint], undefined>,
  'applyForJob' : ActorMethod<[bigint], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createJobListing' : ActorMethod<[JobListing], undefined>,
  'createOrUpdateJobProfile' : ActorMethod<[JobProfile], undefined>,
  'createOrUpdateMatrimonialProfile' : ActorMethod<
    [MatrimonialProfile],
    undefined
  >,
  'deleteJobListing' : ActorMethod<[bigint], undefined>,
  'deleteUser' : ActorMethod<[Principal], undefined>,
  'getAllUsers' : ActorMethod<[], Array<Principal>>,
  'getCallerJobApplications' : ActorMethod<[], Array<JobApplication>>,
  'getCallerMatches' : ActorMethod<[], Array<Match>>,
  'getCallerMessages' : ActorMethod<[Principal], Array<Message>>,
  'getCallerReceivedInterests' : ActorMethod<[], Array<Interest>>,
  'getCallerSentInterests' : ActorMethod<[], Array<Interest>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getJobApplicationsByApplicant' : ActorMethod<
    [Principal],
    Array<JobApplication>
  >,
  'getJobApplicationsByJobId' : ActorMethod<[bigint], Array<JobApplication>>,
  'getJobListingById' : ActorMethod<[bigint], JobListing>,
  'getJobListings' : ActorMethod<[], Array<JobListing>>,
  'getJobProfile' : ActorMethod<[Principal], [] | [JobProfile]>,
  'getMatrimonialProfile' : ActorMethod<[Principal], [] | [MatrimonialProfile]>,
  'getMessages' : ActorMethod<[Principal, Principal], Array<Message>>,
  'getRecommendationsForCaller' : ActorMethod<[], AIRecommendationResult>,
  'getRecommendedJobsForCaller' : ActorMethod<[], Array<JobRecommendation>>,
  'getRecommendedMatchesForCaller' : ActorMethod<
    [],
    Array<MatrimonialRecommendation>
  >,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'initializeAccessControl' : ActorMethod<[], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'rejectInterest' : ActorMethod<[bigint], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'saveMatch' : ActorMethod<[Principal, bigint], undefined>,
  'sendInterest' : ActorMethod<[Principal], undefined>,
  'sendMessage' : ActorMethod<[Principal, string], undefined>,
  'updateApplicationStatus' : ActorMethod<[bigint, string], undefined>,
  'updateJobListing' : ActorMethod<[bigint, JobListing], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];