/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0-beta.9.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const JobListing = IDL.Record({
  'id' : IDL.Nat,
  'experienceLevel' : IDL.Text,
  'title' : IDL.Text,
  'jobType' : IDL.Text,
  'company' : IDL.Text,
  'category' : IDL.Text,
  'salaryRange' : IDL.Tuple(IDL.Nat, IDL.Nat),
  'location' : IDL.Text,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const JobProfile = IDL.Record({
  'resume' : IDL.Opt(ExternalBlob),
  'name' : IDL.Text,
  'maxSalary' : IDL.Nat,
  'education' : IDL.Text,
  'profession' : IDL.Text,
  'minSalary' : IDL.Nat,
  'experience' : IDL.Nat,
  'location' : IDL.Text,
});
export const MatrimonialProfile = IDL.Record({
  'age' : IDL.Nat,
  'occupation' : IDL.Text,
  'name' : IDL.Text,
  'minAge' : IDL.Nat,
  'preferredLocation' : IDL.Text,
  'maxAge' : IDL.Nat,
  'religion' : IDL.Text,
  'profilePicture' : IDL.Opt(ExternalBlob),
});
export const JobApplication = IDL.Record({
  'status' : IDL.Text,
  'applicant' : IDL.Principal,
  'jobId' : IDL.Nat,
  'dateApplied' : IDL.Nat,
});
export const Match = IDL.Record({
  'compatibilityScore' : IDL.Nat,
  'user1' : IDL.Principal,
  'user2' : IDL.Principal,
});
export const Message = IDL.Record({
  'to' : IDL.Principal,
  'content' : IDL.Text,
  'from' : IDL.Principal,
  'timestamp' : IDL.Nat,
});
export const Interest = IDL.Record({
  'status' : IDL.Text,
  'recipient' : IDL.Principal,
  'sender' : IDL.Principal,
});
export const UserProfile = IDL.Record({
  'matrimonialProfile' : IDL.Opt(MatrimonialProfile),
  'jobProfile' : IDL.Opt(JobProfile),
});
export const JobRecommendation = IDL.Record({
  'job' : JobListing,
  'matchScore' : IDL.Nat,
  'reason' : IDL.Text,
});
export const MatrimonialRecommendation = IDL.Record({
  'compatibilityScore' : IDL.Nat,
  'profile' : MatrimonialProfile,
  'reason' : IDL.Text,
});
export const Recommendations = IDL.Record({
  'jobs' : IDL.Vec(JobRecommendation),
  'matches' : IDL.Vec(MatrimonialRecommendation),
});
export const AIRecommendationResult = IDL.Record({
  'recommendations' : Recommendations,
  'explanations' : IDL.Vec(IDL.Text),
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  'acceptInterest' : IDL.Func([IDL.Nat], [], []),
  'applyForJob' : IDL.Func([IDL.Nat], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createJobListing' : IDL.Func([JobListing], [], []),
  'createOrUpdateJobProfile' : IDL.Func([JobProfile], [], []),
  'createOrUpdateMatrimonialProfile' : IDL.Func([MatrimonialProfile], [], []),
  'deleteJobListing' : IDL.Func([IDL.Nat], [], []),
  'deleteUser' : IDL.Func([IDL.Principal], [], []),
  'getAllUsers' : IDL.Func([], [IDL.Vec(IDL.Principal)], ['query']),
  'getCallerJobApplications' : IDL.Func(
      [],
      [IDL.Vec(JobApplication)],
      ['query'],
    ),
  'getCallerMatches' : IDL.Func([], [IDL.Vec(Match)], ['query']),
  'getCallerMessages' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(Message)],
      ['query'],
    ),
  'getCallerReceivedInterests' : IDL.Func([], [IDL.Vec(Interest)], ['query']),
  'getCallerSentInterests' : IDL.Func([], [IDL.Vec(Interest)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getJobApplicationsByApplicant' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(JobApplication)],
      ['query'],
    ),
  'getJobApplicationsByJobId' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(JobApplication)],
      ['query'],
    ),
  'getJobListingById' : IDL.Func([IDL.Nat], [JobListing], ['query']),
  'getJobListings' : IDL.Func([], [IDL.Vec(JobListing)], ['query']),
  'getJobProfile' : IDL.Func([IDL.Principal], [IDL.Opt(JobProfile)], ['query']),
  'getMatrimonialProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(MatrimonialProfile)],
      ['query'],
    ),
  'getMessages' : IDL.Func(
      [IDL.Principal, IDL.Principal],
      [IDL.Vec(Message)],
      ['query'],
    ),
  'getRecommendationsForCaller' : IDL.Func(
      [],
      [AIRecommendationResult],
      ['query'],
    ),
  'getRecommendedJobsForCaller' : IDL.Func(
      [],
      [IDL.Vec(JobRecommendation)],
      ['query'],
    ),
  'getRecommendedMatchesForCaller' : IDL.Func(
      [],
      [IDL.Vec(MatrimonialRecommendation)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'initializeAccessControl' : IDL.Func([], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'rejectInterest' : IDL.Func([IDL.Nat], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'saveMatch' : IDL.Func([IDL.Principal, IDL.Nat], [], []),
  'sendInterest' : IDL.Func([IDL.Principal], [], []),
  'sendMessage' : IDL.Func([IDL.Principal, IDL.Text], [], []),
  'updateApplicationStatus' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'updateJobListing' : IDL.Func([IDL.Nat, JobListing], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const JobListing = IDL.Record({
    'id' : IDL.Nat,
    'experienceLevel' : IDL.Text,
    'title' : IDL.Text,
    'jobType' : IDL.Text,
    'company' : IDL.Text,
    'category' : IDL.Text,
    'salaryRange' : IDL.Tuple(IDL.Nat, IDL.Nat),
    'location' : IDL.Text,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const JobProfile = IDL.Record({
    'resume' : IDL.Opt(ExternalBlob),
    'name' : IDL.Text,
    'maxSalary' : IDL.Nat,
    'education' : IDL.Text,
    'profession' : IDL.Text,
    'minSalary' : IDL.Nat,
    'experience' : IDL.Nat,
    'location' : IDL.Text,
  });
  const MatrimonialProfile = IDL.Record({
    'age' : IDL.Nat,
    'occupation' : IDL.Text,
    'name' : IDL.Text,
    'minAge' : IDL.Nat,
    'preferredLocation' : IDL.Text,
    'maxAge' : IDL.Nat,
    'religion' : IDL.Text,
    'profilePicture' : IDL.Opt(ExternalBlob),
  });
  const JobApplication = IDL.Record({
    'status' : IDL.Text,
    'applicant' : IDL.Principal,
    'jobId' : IDL.Nat,
    'dateApplied' : IDL.Nat,
  });
  const Match = IDL.Record({
    'compatibilityScore' : IDL.Nat,
    'user1' : IDL.Principal,
    'user2' : IDL.Principal,
  });
  const Message = IDL.Record({
    'to' : IDL.Principal,
    'content' : IDL.Text,
    'from' : IDL.Principal,
    'timestamp' : IDL.Nat,
  });
  const Interest = IDL.Record({
    'status' : IDL.Text,
    'recipient' : IDL.Principal,
    'sender' : IDL.Principal,
  });
  const UserProfile = IDL.Record({
    'matrimonialProfile' : IDL.Opt(MatrimonialProfile),
    'jobProfile' : IDL.Opt(JobProfile),
  });
  const JobRecommendation = IDL.Record({
    'job' : JobListing,
    'matchScore' : IDL.Nat,
    'reason' : IDL.Text,
  });
  const MatrimonialRecommendation = IDL.Record({
    'compatibilityScore' : IDL.Nat,
    'profile' : MatrimonialProfile,
    'reason' : IDL.Text,
  });
  const Recommendations = IDL.Record({
    'jobs' : IDL.Vec(JobRecommendation),
    'matches' : IDL.Vec(MatrimonialRecommendation),
  });
  const AIRecommendationResult = IDL.Record({
    'recommendations' : Recommendations,
    'explanations' : IDL.Vec(IDL.Text),
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    'acceptInterest' : IDL.Func([IDL.Nat], [], []),
    'applyForJob' : IDL.Func([IDL.Nat], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createJobListing' : IDL.Func([JobListing], [], []),
    'createOrUpdateJobProfile' : IDL.Func([JobProfile], [], []),
    'createOrUpdateMatrimonialProfile' : IDL.Func([MatrimonialProfile], [], []),
    'deleteJobListing' : IDL.Func([IDL.Nat], [], []),
    'deleteUser' : IDL.Func([IDL.Principal], [], []),
    'getAllUsers' : IDL.Func([], [IDL.Vec(IDL.Principal)], ['query']),
    'getCallerJobApplications' : IDL.Func(
        [],
        [IDL.Vec(JobApplication)],
        ['query'],
      ),
    'getCallerMatches' : IDL.Func([], [IDL.Vec(Match)], ['query']),
    'getCallerMessages' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(Message)],
        ['query'],
      ),
    'getCallerReceivedInterests' : IDL.Func([], [IDL.Vec(Interest)], ['query']),
    'getCallerSentInterests' : IDL.Func([], [IDL.Vec(Interest)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getJobApplicationsByApplicant' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(JobApplication)],
        ['query'],
      ),
    'getJobApplicationsByJobId' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(JobApplication)],
        ['query'],
      ),
    'getJobListingById' : IDL.Func([IDL.Nat], [JobListing], ['query']),
    'getJobListings' : IDL.Func([], [IDL.Vec(JobListing)], ['query']),
    'getJobProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(JobProfile)],
        ['query'],
      ),
    'getMatrimonialProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(MatrimonialProfile)],
        ['query'],
      ),
    'getMessages' : IDL.Func(
        [IDL.Principal, IDL.Principal],
        [IDL.Vec(Message)],
        ['query'],
      ),
    'getRecommendationsForCaller' : IDL.Func(
        [],
        [AIRecommendationResult],
        ['query'],
      ),
    'getRecommendedJobsForCaller' : IDL.Func(
        [],
        [IDL.Vec(JobRecommendation)],
        ['query'],
      ),
    'getRecommendedMatchesForCaller' : IDL.Func(
        [],
        [IDL.Vec(MatrimonialRecommendation)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'initializeAccessControl' : IDL.Func([], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'rejectInterest' : IDL.Func([IDL.Nat], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'saveMatch' : IDL.Func([IDL.Principal, IDL.Nat], [], []),
    'sendInterest' : IDL.Func([IDL.Principal], [], []),
    'sendMessage' : IDL.Func([IDL.Principal, IDL.Text], [], []),
    'updateApplicationStatus' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'updateJobListing' : IDL.Func([IDL.Nat, JobListing], [], []),
  });
};

export const init = ({ IDL }) => { return []; };