/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0-beta.9.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface MatrimonialRecommendation {
    compatibilityScore: bigint;
    profile: MatrimonialProfile;
    reason: string;
}
export interface JobProfile {
    resume?: ExternalBlob;
    name: string;
    maxSalary: bigint;
    education: string;
    profession: string;
    minSalary: bigint;
    experience: bigint;
    location: string;
}
export interface JobRecommendation {
    job: JobListing;
    matchScore: bigint;
    reason: string;
}
export interface JobListing {
    id: bigint;
    experienceLevel: string;
    title: string;
    jobType: string;
    company: string;
    category: string;
    salaryRange: [bigint, bigint];
    location: string;
}
export interface JobApplication {
    status: string;
    applicant: Principal;
    jobId: bigint;
    dateApplied: bigint;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface Recommendations {
    jobs: Array<JobRecommendation>;
    matches: Array<MatrimonialRecommendation>;
}
export interface Match {
    compatibilityScore: bigint;
    user1: Principal;
    user2: Principal;
}
export interface Interest {
    status: string;
    recipient: Principal;
    sender: Principal;
}
export interface Message {
    to: Principal;
    content: string;
    from: Principal;
    timestamp: bigint;
}
export interface MatrimonialProfile {
    age: bigint;
    occupation: string;
    name: string;
    minAge: bigint;
    preferredLocation: string;
    maxAge: bigint;
    religion: string;
    profilePicture?: ExternalBlob;
}
export interface AIRecommendationResult {
    recommendations: Recommendations;
    explanations: Array<string>;
}
export interface UserProfile {
    matrimonialProfile?: MatrimonialProfile;
    jobProfile?: JobProfile;
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    acceptInterest(interestId: bigint): Promise<void>;
    applyForJob(jobId: bigint): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createJobListing(listing: JobListing): Promise<void>;
    createOrUpdateJobProfile(profile: JobProfile): Promise<void>;
    createOrUpdateMatrimonialProfile(profile: MatrimonialProfile): Promise<void>;
    deleteJobListing(jobId: bigint): Promise<void>;
    deleteUser(user: Principal): Promise<void>;
    getAllUsers(): Promise<Array<Principal>>;
    getCallerJobApplications(): Promise<Array<JobApplication>>;
    getCallerMatches(): Promise<Array<Match>>;
    getCallerMessages(otherUser: Principal): Promise<Array<Message>>;
    getCallerReceivedInterests(): Promise<Array<Interest>>;
    getCallerSentInterests(): Promise<Array<Interest>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getJobApplicationsByApplicant(applicant: Principal): Promise<Array<JobApplication>>;
    getJobApplicationsByJobId(jobId: bigint): Promise<Array<JobApplication>>;
    getJobListingById(jobId: bigint): Promise<JobListing>;
    getJobListings(): Promise<Array<JobListing>>;
    getJobProfile(user: Principal): Promise<JobProfile | null>;
    getMatrimonialProfile(user: Principal): Promise<MatrimonialProfile | null>;
    getMessages(user1: Principal, user2: Principal): Promise<Array<Message>>;
    getRecommendationsForCaller(): Promise<AIRecommendationResult>;
    getRecommendedJobsForCaller(): Promise<Array<JobRecommendation>>;
    getRecommendedMatchesForCaller(): Promise<Array<MatrimonialRecommendation>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    initializeAccessControl(): Promise<void>;
    isCallerAdmin(): Promise<boolean>;
    rejectInterest(interestId: bigint): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    saveMatch(user2: Principal, compatibility: bigint): Promise<void>;
    sendInterest(recipient: Principal): Promise<void>;
    sendMessage(to: Principal, content: string): Promise<void>;
    updateApplicationStatus(applicationId: bigint, status: string): Promise<void>;
    updateJobListing(jobId: bigint, listing: JobListing): Promise<void>;
}
import type { AIRecommendationResult as _AIRecommendationResult, ExternalBlob as _ExternalBlob, JobProfile as _JobProfile, JobRecommendation as _JobRecommendation, MatrimonialProfile as _MatrimonialProfile, MatrimonialRecommendation as _MatrimonialRecommendation, Recommendations as _Recommendations, UserProfile as _UserProfile, UserRole as _UserRole, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this.uploadFile, this.downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this.uploadFile, this.downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this.uploadFile, this.downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async acceptInterest(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.acceptInterest(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.acceptInterest(arg0);
            return result;
        }
    }
    async applyForJob(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.applyForJob(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.applyForJob(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this.uploadFile, this.downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this.uploadFile, this.downloadFile, arg1));
            return result;
        }
    }
    async createJobListing(arg0: JobListing): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createJobListing(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createJobListing(arg0);
            return result;
        }
    }
    async createOrUpdateJobProfile(arg0: JobProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createOrUpdateJobProfile(await to_candid_JobProfile_n10(this.uploadFile, this.downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createOrUpdateJobProfile(await to_candid_JobProfile_n10(this.uploadFile, this.downloadFile, arg0));
            return result;
        }
    }
    async createOrUpdateMatrimonialProfile(arg0: MatrimonialProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createOrUpdateMatrimonialProfile(await to_candid_MatrimonialProfile_n13(this.uploadFile, this.downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createOrUpdateMatrimonialProfile(await to_candid_MatrimonialProfile_n13(this.uploadFile, this.downloadFile, arg0));
            return result;
        }
    }
    async deleteJobListing(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteJobListing(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteJobListing(arg0);
            return result;
        }
    }
    async deleteUser(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteUser(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteUser(arg0);
            return result;
        }
    }
    async getAllUsers(): Promise<Array<Principal>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllUsers();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllUsers();
            return result;
        }
    }
    async getCallerJobApplications(): Promise<Array<JobApplication>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerJobApplications();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerJobApplications();
            return result;
        }
    }
    async getCallerMatches(): Promise<Array<Match>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerMatches();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerMatches();
            return result;
        }
    }
    async getCallerMessages(arg0: Principal): Promise<Array<Message>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerMessages(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerMessages(arg0);
            return result;
        }
    }
    async getCallerReceivedInterests(): Promise<Array<Interest>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerReceivedInterests();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerReceivedInterests();
            return result;
        }
    }
    async getCallerSentInterests(): Promise<Array<Interest>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerSentInterests();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerSentInterests();
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n15(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n15(this.uploadFile, this.downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n26(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n26(this.uploadFile, this.downloadFile, result);
        }
    }
    async getJobApplicationsByApplicant(arg0: Principal): Promise<Array<JobApplication>> {
        if (this.processError) {
            try {
                const result = await this.actor.getJobApplicationsByApplicant(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getJobApplicationsByApplicant(arg0);
            return result;
        }
    }
    async getJobApplicationsByJobId(arg0: bigint): Promise<Array<JobApplication>> {
        if (this.processError) {
            try {
                const result = await this.actor.getJobApplicationsByJobId(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getJobApplicationsByJobId(arg0);
            return result;
        }
    }
    async getJobListingById(arg0: bigint): Promise<JobListing> {
        if (this.processError) {
            try {
                const result = await this.actor.getJobListingById(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getJobListingById(arg0);
            return result;
        }
    }
    async getJobListings(): Promise<Array<JobListing>> {
        if (this.processError) {
            try {
                const result = await this.actor.getJobListings();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getJobListings();
            return result;
        }
    }
    async getJobProfile(arg0: Principal): Promise<JobProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getJobProfile(arg0);
                return from_candid_opt_n23(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getJobProfile(arg0);
            return from_candid_opt_n23(this.uploadFile, this.downloadFile, result);
        }
    }
    async getMatrimonialProfile(arg0: Principal): Promise<MatrimonialProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMatrimonialProfile(arg0);
                return from_candid_opt_n18(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMatrimonialProfile(arg0);
            return from_candid_opt_n18(this.uploadFile, this.downloadFile, result);
        }
    }
    async getMessages(arg0: Principal, arg1: Principal): Promise<Array<Message>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMessages(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMessages(arg0, arg1);
            return result;
        }
    }
    async getRecommendationsForCaller(): Promise<AIRecommendationResult> {
        if (this.processError) {
            try {
                const result = await this.actor.getRecommendationsForCaller();
                return from_candid_AIRecommendationResult_n28(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRecommendationsForCaller();
            return from_candid_AIRecommendationResult_n28(this.uploadFile, this.downloadFile, result);
        }
    }
    async getRecommendedJobsForCaller(): Promise<Array<JobRecommendation>> {
        if (this.processError) {
            try {
                const result = await this.actor.getRecommendedJobsForCaller();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRecommendedJobsForCaller();
            return result;
        }
    }
    async getRecommendedMatchesForCaller(): Promise<Array<MatrimonialRecommendation>> {
        if (this.processError) {
            try {
                const result = await this.actor.getRecommendedMatchesForCaller();
                return from_candid_vec_n32(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRecommendedMatchesForCaller();
            return from_candid_vec_n32(this.uploadFile, this.downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n15(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n15(this.uploadFile, this.downloadFile, result);
        }
    }
    async initializeAccessControl(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.initializeAccessControl();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.initializeAccessControl();
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async rejectInterest(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.rejectInterest(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.rejectInterest(arg0);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(await to_candid_UserProfile_n35(this.uploadFile, this.downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(await to_candid_UserProfile_n35(this.uploadFile, this.downloadFile, arg0));
            return result;
        }
    }
    async saveMatch(arg0: Principal, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveMatch(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveMatch(arg0, arg1);
            return result;
        }
    }
    async sendInterest(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.sendInterest(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.sendInterest(arg0);
            return result;
        }
    }
    async sendMessage(arg0: Principal, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.sendMessage(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.sendMessage(arg0, arg1);
            return result;
        }
    }
    async updateApplicationStatus(arg0: bigint, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateApplicationStatus(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateApplicationStatus(arg0, arg1);
            return result;
        }
    }
    async updateJobListing(arg0: bigint, arg1: JobListing): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateJobListing(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateJobListing(arg0, arg1);
            return result;
        }
    }
}
async function from_candid_AIRecommendationResult_n28(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AIRecommendationResult): Promise<AIRecommendationResult> {
    return await from_candid_record_n29(uploadFile, downloadFile, value);
}
async function from_candid_ExternalBlob_n22(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await downloadFile(value);
}
async function from_candid_JobProfile_n24(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _JobProfile): Promise<JobProfile> {
    return await from_candid_record_n25(uploadFile, downloadFile, value);
}
async function from_candid_MatrimonialProfile_n19(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MatrimonialProfile): Promise<MatrimonialProfile> {
    return await from_candid_record_n20(uploadFile, downloadFile, value);
}
async function from_candid_MatrimonialRecommendation_n33(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MatrimonialRecommendation): Promise<MatrimonialRecommendation> {
    return await from_candid_record_n34(uploadFile, downloadFile, value);
}
async function from_candid_Recommendations_n30(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Recommendations): Promise<Recommendations> {
    return await from_candid_record_n31(uploadFile, downloadFile, value);
}
async function from_candid_UserProfile_n16(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): Promise<UserProfile> {
    return await from_candid_record_n17(uploadFile, downloadFile, value);
}
function from_candid_UserRole_n26(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n27(uploadFile, downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(uploadFile, downloadFile, value);
}
async function from_candid_opt_n15(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): Promise<UserProfile | null> {
    return value.length === 0 ? null : await from_candid_UserProfile_n16(uploadFile, downloadFile, value[0]);
}
async function from_candid_opt_n18(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_MatrimonialProfile]): Promise<MatrimonialProfile | null> {
    return value.length === 0 ? null : await from_candid_MatrimonialProfile_n19(uploadFile, downloadFile, value[0]);
}
async function from_candid_opt_n21(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ExternalBlob]): Promise<ExternalBlob | null> {
    return value.length === 0 ? null : await from_candid_ExternalBlob_n22(uploadFile, downloadFile, value[0]);
}
async function from_candid_opt_n23(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_JobProfile]): Promise<JobProfile | null> {
    return value.length === 0 ? null : await from_candid_JobProfile_n24(uploadFile, downloadFile, value[0]);
}
function from_candid_opt_n6(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_record_n17(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    matrimonialProfile: [] | [_MatrimonialProfile];
    jobProfile: [] | [_JobProfile];
}): Promise<{
    matrimonialProfile?: MatrimonialProfile;
    jobProfile?: JobProfile;
}> {
    return {
        matrimonialProfile: record_opt_to_undefined(await from_candid_opt_n18(uploadFile, downloadFile, value.matrimonialProfile)),
        jobProfile: record_opt_to_undefined(await from_candid_opt_n23(uploadFile, downloadFile, value.jobProfile))
    };
}
async function from_candid_record_n20(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    age: bigint;
    occupation: string;
    name: string;
    minAge: bigint;
    preferredLocation: string;
    maxAge: bigint;
    religion: string;
    profilePicture: [] | [_ExternalBlob];
}): Promise<{
    age: bigint;
    occupation: string;
    name: string;
    minAge: bigint;
    preferredLocation: string;
    maxAge: bigint;
    religion: string;
    profilePicture?: ExternalBlob;
}> {
    return {
        age: value.age,
        occupation: value.occupation,
        name: value.name,
        minAge: value.minAge,
        preferredLocation: value.preferredLocation,
        maxAge: value.maxAge,
        religion: value.religion,
        profilePicture: record_opt_to_undefined(await from_candid_opt_n21(uploadFile, downloadFile, value.profilePicture))
    };
}
async function from_candid_record_n25(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    resume: [] | [_ExternalBlob];
    name: string;
    maxSalary: bigint;
    education: string;
    profession: string;
    minSalary: bigint;
    experience: bigint;
    location: string;
}): Promise<{
    resume?: ExternalBlob;
    name: string;
    maxSalary: bigint;
    education: string;
    profession: string;
    minSalary: bigint;
    experience: bigint;
    location: string;
}> {
    return {
        resume: record_opt_to_undefined(await from_candid_opt_n21(uploadFile, downloadFile, value.resume)),
        name: value.name,
        maxSalary: value.maxSalary,
        education: value.education,
        profession: value.profession,
        minSalary: value.minSalary,
        experience: value.experience,
        location: value.location
    };
}
async function from_candid_record_n29(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    recommendations: _Recommendations;
    explanations: Array<string>;
}): Promise<{
    recommendations: Recommendations;
    explanations: Array<string>;
}> {
    return {
        recommendations: await from_candid_Recommendations_n30(uploadFile, downloadFile, value.recommendations),
        explanations: value.explanations
    };
}
async function from_candid_record_n31(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    jobs: Array<_JobRecommendation>;
    matches: Array<_MatrimonialRecommendation>;
}): Promise<{
    jobs: Array<JobRecommendation>;
    matches: Array<MatrimonialRecommendation>;
}> {
    return {
        jobs: value.jobs,
        matches: await from_candid_vec_n32(uploadFile, downloadFile, value.matches)
    };
}
async function from_candid_record_n34(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    compatibilityScore: bigint;
    profile: _MatrimonialProfile;
    reason: string;
}): Promise<{
    compatibilityScore: bigint;
    profile: MatrimonialProfile;
    reason: string;
}> {
    return {
        compatibilityScore: value.compatibilityScore,
        profile: await from_candid_MatrimonialProfile_n19(uploadFile, downloadFile, value.profile),
        reason: value.reason
    };
}
function from_candid_record_n5(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(uploadFile, downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(uploadFile, downloadFile, value.topped_up_amount))
    };
}
function from_candid_variant_n27(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
async function from_candid_vec_n32(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_MatrimonialRecommendation>): Promise<Array<MatrimonialRecommendation>> {
    return await Promise.all(value.map(async (x)=>await from_candid_MatrimonialRecommendation_n33(uploadFile, downloadFile, x)));
}
async function to_candid_ExternalBlob_n12(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await uploadFile(value);
}
async function to_candid_JobProfile_n10(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: JobProfile): Promise<_JobProfile> {
    return await to_candid_record_n11(uploadFile, downloadFile, value);
}
async function to_candid_MatrimonialProfile_n13(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MatrimonialProfile): Promise<_MatrimonialProfile> {
    return await to_candid_record_n14(uploadFile, downloadFile, value);
}
async function to_candid_UserProfile_n35(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): Promise<_UserProfile> {
    return await to_candid_record_n36(uploadFile, downloadFile, value);
}
function to_candid_UserRole_n8(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n9(uploadFile, downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(uploadFile, downloadFile, value);
}
function to_candid_opt_n1(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(uploadFile, downloadFile, value));
}
async function to_candid_record_n11(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    resume?: ExternalBlob;
    name: string;
    maxSalary: bigint;
    education: string;
    profession: string;
    minSalary: bigint;
    experience: bigint;
    location: string;
}): Promise<{
    resume: [] | [_ExternalBlob];
    name: string;
    maxSalary: bigint;
    education: string;
    profession: string;
    minSalary: bigint;
    experience: bigint;
    location: string;
}> {
    return {
        resume: value.resume ? candid_some(await to_candid_ExternalBlob_n12(uploadFile, downloadFile, value.resume)) : candid_none(),
        name: value.name,
        maxSalary: value.maxSalary,
        education: value.education,
        profession: value.profession,
        minSalary: value.minSalary,
        experience: value.experience,
        location: value.location
    };
}
async function to_candid_record_n14(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    age: bigint;
    occupation: string;
    name: string;
    minAge: bigint;
    preferredLocation: string;
    maxAge: bigint;
    religion: string;
    profilePicture?: ExternalBlob;
}): Promise<{
    age: bigint;
    occupation: string;
    name: string;
    minAge: bigint;
    preferredLocation: string;
    maxAge: bigint;
    religion: string;
    profilePicture: [] | [_ExternalBlob];
}> {
    return {
        age: value.age,
        occupation: value.occupation,
        name: value.name,
        minAge: value.minAge,
        preferredLocation: value.preferredLocation,
        maxAge: value.maxAge,
        religion: value.religion,
        profilePicture: value.profilePicture ? candid_some(await to_candid_ExternalBlob_n12(uploadFile, downloadFile, value.profilePicture)) : candid_none()
    };
}
function to_candid_record_n3(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
async function to_candid_record_n36(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    matrimonialProfile?: MatrimonialProfile;
    jobProfile?: JobProfile;
}): Promise<{
    matrimonialProfile: [] | [_MatrimonialProfile];
    jobProfile: [] | [_JobProfile];
}> {
    return {
        matrimonialProfile: value.matrimonialProfile ? candid_some(await to_candid_MatrimonialProfile_n13(uploadFile, downloadFile, value.matrimonialProfile)) : candid_none(),
        jobProfile: value.jobProfile ? candid_some(await to_candid_JobProfile_n10(uploadFile, downloadFile, value.jobProfile)) : candid_none()
    };
}
function to_candid_variant_n9(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, uploadFile, downloadFile, options.processError);
}
